// <auto-generated />
namespace Quiz_Maker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class uer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uer));
        
        string IMigrationMetadata.Id
        {
            get { return "202002291516520_uer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
